# Generated by Django 5.1.4 on 2025-01-17 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_nav_alter_category_options_alter_post_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nav',
            name='urlpath',
            field=models.CharField(max_length=255),
        ),
    ]
