# Generated by Django 5.1.4 on 2025-01-19 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_post_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subtitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Fragment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_type', models.CharField(choices=[('p', 'Paragraf (p)'), ('span', 'span'), ('br', 'Boşluk (br)'), ('pre', 'Kod satırı (pre)'), ('strong', 'Kalın metin (strong)'), ('i', 'İtalik Metin (i)'), ('a', 'URL (a)'), ('h1', 'Başlık (h1)'), ('h2', 'Başlık (h2)'), ('h3', 'Başlık (h3)'), ('h4', 'Başlık (h4) (Kırmızı)'), ('h5', 'Başlık (h5) (Sarı)'), ('h6', 'Başlık (h6) (Yeşil)')], default='p', max_length=200)),
                ('content', models.TextField()),
                ('subtitle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.subtitle')),
            ],
        ),
        migrations.AddField(
            model_name='subtitle',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.title'),
        ),
    ]
