# Generated by Django 5.1.4 on 2025-01-19 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_subtitle_title_fragment_subtitle_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='fragment',
            name='order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
