# Generated by Django 5.1.4 on 2025-01-20 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_rename_title_category_category_title_title_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtitle',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
